language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
 - php vendor/bin/coveralls --exclude-no-stmt
